version: '2'
volumes:
    ldap_data:
services:
  vpn:
    #build: ..
    image: jenkinsciinfra/openvpn@sha256:da7df2af12676863b3aa4b52e48650a8ba11692a0cbf582f86c7425945160496
    cap_add:
        - NET_ADMIN
    depends_on:
        - ldap
    environment:
        - "AUTH_LDAP_PASSWORD=s3cr3t"
        - "AUTH_LDAP_URL=ldaps://ldap"
        - "AUTH_LDAP_BINDDN=cn=admin,dc=jenkins-ci,dc=org"
        - "AUTH_LDAP_GROUPS_MEMBER=cn=all"
    volumes:
        - ./mock/vpn/ccd:/etc/openvpn/server/ccd
        - ./mock/vpn/ca.crt:/etc/openvpn/server/ca.crt
        - ./mock/vpn/ldapca.crt:/etc/ldap/ssl/cacert.crt
        - ./mock/vpn/vpn.crt:/etc/openvpn/server/server.crt
        - ./mock/vpn/dh.pem:/etc/openvpn/server/dh.pem
        - ./mock/vpn/vpn.key:/etc/openvpn/server/server.key
        - ./mock/vpn/ca.crt:/etc/ssl/certs/ca-certificates.crt
    ports:
        - 443:443

  # Don't forget to run /entrypoint/restore, once database is started
  ldap:
    image: jenkinsciinfra/ldap@sha256:bee8e769077e82984ada23d25b06c7f42130a4b9f9fa92ead20916e01c1af8de
    environment:
        - "OPENLDAP_DEBUG_LEVEL=1"
    volumes:
        - ldap_data:/var/lib/ldap
        - ./mock/ldap/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
        - ./mock/ldap/ca.crt:/etc/ldap/ssl-ca/ca.crt:ro # Override the Let's Encrypt CA embeded in the image
        - ./mock/ldap/ldap.crt:/etc/ldap/ssl/cert.pem:ro
        - ./mock/ldap/ldap.key:/etc/ldap/ssl/privkey.key:ro
        - ./mock/mock.ldif:/var/backups/backup.latest.ldif:ro
